<?php

/**
 * @file
 * Contains di_nodes_person.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function di_nodes_person_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the di_nodes_person module.
    case 'help.page.di_nodes_person':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Person content type and related fields for Digital Initiatives projects.') . '</p>';
      return $output;

    default:
  }
}
