<?php

/**
 * @file
 * Contains di_nodes_page.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function di_nodes_page_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the di_nodes_page module.
    case 'help.page.di_nodes_page':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Neat basic page content type and fields.') . '</p>';
      return $output;

    default:
  }
}
